# Build options
LTO_ENABLE = yes

# QMK
BOOTMAGIC_ENABLE = no
OLED_ENABLE = no
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no

QMK_SETTINGS = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes
LEADER_ENABLE = yes
AUTO_SHIFT_ENABLE = yes

# Encoder support
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# Vial
VIA_ENABLE = yes
VIAL_ENABLE = yes
